game_features:
 distWall1 : False
 distWall2 : False
 distWall3 : False
 distWall4 : False
 distFood1 : True
 distFood2 : True
 distOwnBody1 : False
 distOwnBody2 : False
 distOwnBody3 : False
 distOwnBody4 : False
 OldDir : False
 NewDir : False

nn: # last layer should always have 4 neurons
 n_layers: 5
 epochs: 25
 batch_size: 10
 1_layer: 10 # input layer
 2_layer: 10
 3_layer: 8
 4_layer: 8
 5_layer: 4
 6_layer: 4

rotation_help: True
