game_features:
 distWall1 : False
 distWall2 : False
 distWall3 : False
 distWall4 : False
 distFood1 : True
 distFood2 : True
 distOwnBody1 : False
 distOwnBody2 : False
 distOwnBody3 : False
 distOwnBody4 : False
 OldDir : False
 NewDir : False

nn: # last layer should always have 4 neurons
 n_layers: 4
 epochs: 40
 batch_size: 20
 1_layer: 18 # input layer
 2_layer: 18
 3_layer: 6
 4_layer: 4
 5_layer: 16
 6_layer: 16
 7_layer: 16
 8_layer: 8
 9_layer: 4

rotation_help: True
